mlcvs/models/linear.py, mlcvs/models/nn.py, mlcvs/tests/test_lda_linear.py, mlcvs/tica/deep_tica.py, mlcvs/tica/linear_tica.py, mlcvs/tica/tica.py, mlcvs/utils/data.py
- check what happens if the correlation matrices are not symmetric
=> Tprime evaluation and Solve TICA problem with not-symmetric Correlation Matrix

mlcvs/core/loss/__init__.py, mlcvs/core/loss/elbo.py, mlcvs/cvs/unsupervised/vae.py, mlcvs/tests/test_cvs_unsupervised_vae.py
This implements a CV based on a standard variational autoencoder using a MSE reconstruction loss and regularizing with a KL divergence w.r.t. a ``Normal(0, 1)`` distribution. For the CV, only the mean is used as CV in production.
=> First implementation of a Variation Autoencoder CV

mlcvs/core/loss/elbo.py, mlcvs/cvs/unsupervised/autoencoder.py, mlcvs/cvs/unsupervised/vae.py
I added a small feature to the training step of AE/VAE cvs to allow comparing the output of the decoder not only with the input data but also with different quantities (e.g. time-lagged data).
If a 'target' key is available in the dictionary it will be used in the reconstruction loss, otherwise 'data' is used.
@andrrizzi
=> add option in ae/vae to compare output of the decoder with a different target

mlcvs/tests/test_utils_io.py, mlcvs/utils/io.py
I cleaned up and extended the `load_dataframe` functions in `utils.io`, now it supports also downloading data from the web (check if the string contains http)
By default, it deletes the file after it has loaded (I also added a delete_download keyword to change this behavior). 
I think it might be useful for having tutorials that use data from published papers to pull them from the related repos.
=> Improve load_dataframe

mlcvs/core/loss/__init__.py, mlcvs/core/loss/autocorrelation.py, mlcvs/core/loss/eigvals.py, mlcvs/core/loss/elbo.py, mlcvs/core/loss/fisher.py, mlcvs/core/loss/mse.py, mlcvs/core/loss/tda_loss.py, mlcvs/cvs/cv.py, mlcvs/cvs/supervised/regression.py
- Implements the class version of all loss functions.
- Fixes the ``RegressionCV`` tests that were not testing weights.
- Some PEP8 fixes (mostly spaces).
- Some docstring extensions.
This PR shouldn't break anything, and it is already quite big so I'm going to merge it and implement the switch from functional to class loss functions in ``cvs`` in a separate PR.
=> Implement Loss classes, some PEP8 fixes

docs/notebooks/cvs_DeepTICA.ipynb, docs/notebooks/intro_3_loss_optim.ipynb, mlcvs/core/loss/tda_loss.py, mlcvs/cvs/cv.py, mlcvs/cvs/supervised/deeplda.py, mlcvs/cvs/supervised/deeptda.py, mlcvs/cvs/supervised/regression.py, mlcvs/cvs/timelagged/deeptica.py, mlcvs/cvs/unsupervised/autoencoder.py, mlcvs/cvs/unsupervised/vae.py
Changes the CV classes to use by default a loss function object.
It is still possible to assign ``loss_fn`` to a (lambda) function, although I had to override ``__setattr__`` to work around some weird PyTorch magic (hopefully the comments I left in the code makes it clear).
=> Switch from functional to class losses

docs/notebooks/cvs_DeepTICA.ipynb, docs/notebooks/cvs_TAE.ipynb, mlcvs/core/loss/autocorrelation.py, mlcvs/core/loss/fisher.py, mlcvs/data/dataloader.py, mlcvs/data/datamodule.py, mlcvs/tests/test_utils_data_dataloader.py, mlcvs/tests/test_utils_data_datamodule.py
This PR adds support for multiple datasets in ``DictionaryDataModule`` and ``FastDictionaryLoader``. I have also extended a bit the tests and the docstrings and added a couple of working doctest examples.
=> Support for multiple datasets

mlcvs/core/loss/autocorrelation.py, mlcvs/core/loss/fisher.py, mlcvs/core/loss/tda_loss.py, mlcvs/core/nn/feedforward.py, mlcvs/core/nn/utils.py, mlcvs/core/stats/utils.py, mlcvs/core/transform/normalization.py, mlcvs/cvs/multitask/__init__.py, mlcvs/cvs/multitask/multitask.py, mlcvs/cvs/supervised/deeptda.py, mlcvs/cvs/unsupervised/vae.py, mlcvs/data/dataloader.py, mlcvs/tests/test_core_model_feedforward.py, mlcvs/tests/test_core_nn_feedforward.py, mlcvs/tests/test_cvs_multitask_multitask.py, mlcvs/tests/test_cvs_unsupervised_vae.py, mlcvs/tests/test_utils_data_dataloader.py
1. Implement ``MultiTaskCV``. Because the class dynamically inherits from the main CV, this doesn't work if the main CV uses ``__slots__`` but I thought this a rare case that we could avoid supporting.
2. Fix ``FastDictionaryLoader.get_stats()``.
- By default, when there are multiple datasets, it computes the stats for all of them unless the ``dataset_idx`` argument is given.
- I've also removed the batch iteration to simplify a bit the code for the multidataset case and because ``DictionaryDataset``s already have everything in memory anyway so this should be slightly faster than doing a for loop.
3. Extended ``AutocorrelationLoss`` and ``FisherDiscriminantLoss`` to multivariate features. I've also added a Lorentzian regularization to ``FisherDiscriminantLoss`` to avoid it to explode.
4. …
=> Multi-task CV and various fixes

mlcolvar/cvs/multitask/__init__.py, mlcolvar/cvs/multitask/multitask.py, mlcolvar/tests/test_cvs_multitask_multitask.py
Task-specific layers can be added within the auxiliary loss functions of ``MultiTaskCV``, and now they will be trained.
=> Support for task-specific layers

.github/workflows/CI.yaml, docs/notebooks/tutorials/cvs_DeepTICA.ipynb, requirements.txt
By mistake in #64 we removed the noteboooks testing. Here we add them back to where they belong and include their testing to the code coverage
=> Include notebook testing to codecov

.github/workflows/CI.yaml
In a previous commit there was aa bug in the test list and the notebooks test were runa also outside Ubuntu, leading to cell-time-limit errors sometimes.
=> Moved notebook tests only to Ubuntu

devtools/conda-envs/test_env.yaml, docs/requirements.yaml
pydantic = 2 is not compatible with lightning (see https://github.com/Lightning-AI/lightning/issues/18027) 
this is a workaround to compile docs and CI while a new patch of lightning is released
=> specify dependency version requirement 

docs/notebooks/tutorials/intro_3_loss_optim.ipynb, mlcolvar/data/datamodule.py, mlcolvar/tests/test_utils_data_datamodule.py, mlcolvar/utils/trainer.py
This PR  fixes #83 
I changed the `DictModule` as to accept a list with just one split. Furthermore, since by default the trainer expects a validation loader, it has to be disabled in the trainer options (see https://github.com/Lightning-AI/lightning/issues/12374) 
I added these instructions in the tutorial on how to customize training
=> Fix disable validation

.github/workflows/CI.yaml
provision-with-micromamba has been migrated to setup-micromamba so the CI test are not running, see #94  
See https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba%60 for details
=> Fix mamba commands migration issue 

mlcolvar/data/datamodule.py
Create a single `split_dataset` function to split datasets in sequential and random mode to fix #91
This deprecates the `sequential_split` function, which becomes a case of the more general `split_dataset` function.
- By default, DeprecationWarnings are not shown. Is it better to print a UserWarning for the `sequential_split` function?
=> general split_dataset functions

README.md
Main page was missing installation info (see #101)
Added information on installing with pip and by cloning the repo
- [x ] Ready to go
=> Add installation info for main page

mlcolvar/utils/plot.py
register_cmap has been deprecated by matplotlib, changing it as described here:
```
MatplotlibDeprecationWarning: The register_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps.register(name)`` instead.
```
=> change register_cmap to register

docs/notebooks/tutorials/adv_features_relevances.ipynb, docs/tutorials_advanced.rst
I just forgot to add the tutorial to the documentation in #108
=> add sensitivity tutorial to doc

mlcolvar/core/loss/tda_loss.py
The current check raised an error even if all labels were present if one of the label was only in the first sample of the batch.
=> Fix bug unrepresented state.

docs/notebooks/tutorials/intro_3_loss_optim.ipynb, mlcolvar/cvs/cv.py
Added the possibility to use torch learning rate scheduler.
They should be passed using the `options` in the CV models
This closes #96
=> Add lr_scheduler options

mlcolvar/core/nn/feedforward.py, mlcolvar/cvs/cv.py, mlcolvar/tests/test_core_nn_feedforward.py
Fix bug of in_place dropout application that makes backprop fail and in batchnorm option, see #118
Also adds a backward call in test for nn.feedforward
=> Bug fix in nn.feedforward

.github/workflows/CI.yaml, devtools/conda-envs/test_env.yaml, mlcolvar/data/datamodule.py
Tests failing:
- General, PyTorch dismissed the _accumulate function we were using in data/datamodule.py 
I added the function explicitly in the datamodule file
- On MacOS 14 because it doesn't support some device-related function anymore apparently
This closes #128 
Check if tests succeed
=> Fix issues in CI 

mlcolvar/core/loss/tda_loss.py
This PR introduces registration of the TDA target parameters (`target_centers` and `target_sigmas`) as buffers within the `TDALoss` module.
- Eliminates the need to convert both parameters to tensors and move them to the current device for each loss calculation step
- Enables retrieval of target parameters from saved `DeepTDA` CV checkpoints or traced modules
=> Register TDA target parameters as loss module buffers

.github/workflows/CI.yaml, .github/workflows/PyPI.yaml, .github/workflows/codeql.yml
Improve continuos integration via github actions and test also the PyPI version to identify dependency issues as in #143.
Suggested by @andrrizzi  in #144 
Notable points that this PR has either accomplished or will accomplish.
=> Test PyPI version via CI

.github/workflows/CI.yaml, devtools/conda-envs/test_env.yaml, mlcolvar/utils/fes.py, requirements.txt
After Numpy's new releases, a few bugs appeared that are related to Numpy and its interaction with Pytorch.
After a couple of weeks they still have not been fixed, the tests are failing and the installation is then unstable.
A temporary fixed should be done. 
This sets numpy<2 in the requirements for now because on macos numpy>2 just doesn't work with pytorch yet.
Also, it fixes preventively this silly issue related to Numpy>2
- `np.meshgrid` output from list to tuple made `compute_fes` crash
Questions
=> Numpy 2 update temporary fixes

README.md, mlcolvar/data/datamodule.py
Fixes two minor doc issues, fixes #149 and fixes #154
=> Doc minor fixes 

docs/conf.py, readthedocs.yml
Add config file to readthedocs.yaml, as it is now mandatory:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> add config file to readthedocs

mlcolvar/core/loss/committor_loss.py, mlcolvar/cvs/committor/utils.py
SmartDerivatives for the committor used to throw an error if some of the input atoms were not used for any descriptors.
This PR adds the possibility of by-passing the issue, for example, for coordination number where useless atoms may be added for padding to preserve the sahep of inputs in different frames.
=> Smart derivatives fix

mlcolvar/core/loss/committor_loss.py, mlcolvar/cvs/committor/utils.py
To fix a bug in smart derivatives related to some descriptors having some zero component of the derivatives (see also #176) I added the option of adding a small noise to the positions in the smart derivatives utils:
- `mlcolvar.core.loss.committor_loss.compute_descriptors_derivatives`
- `mlcolvar.cvs.committor.utils.get_descriptors_and_derivatives`
The default behaviour is unchanged but if the bug is encountered it throws an error pointing to the new option.
This fixes #176
=> Add optional noise to positions in smart derivatives utils

mlcolvar/core/loss/utils/smart_derivatives.py
In some cases, tests were failing because on different OS due to precision issues.
This forces the test to run in double precision.
=> smart derivatives test stability

mlcolvar/utils/fes.py
Setting the min of the fes of each block (fes_i) to 0 doesn't guarantee that the min of the average (fes) is at 0. So in order to have the min of the fes at 0 we can apply the offset after averaging.
In addition, I'm not sure it's right to apply a different offset to each fes_i (i.e. np.nanmin(fes_i)) because this will surely affect the final average. 
Maybe I'm wrong so let me know what you think! :)
=> fix: make sure the average fes has the min at 0

mlcolvar/core/loss/elbo.py, mlcolvar/cvs/unsupervised/vae.py
I was trying to use the VAE CV as it is on my dataset (features from an MD simulation). I quickly noticed that my results were not as nice as in the example in the docs. Even using the same activation function and a small decoder as in the example (mlcolvar/docs/notebooks/tutorials/cvs_Autoencoder.ipynb). I was just observing a "blob" of points without any separation of metastable states:
See PCA on the same data for comparison:
With a bit of help from my favorite AI buddy (I'm not an expert on Deep learning or VAEs) I believe I identified the main issue. The regularization term in the loss together with my choice of hyperparameters and arquitecture were collapsing the latent space to the prior P(z) ~ N(0,I). So the model learned to reduce the loss just by reducing the KL term and mostly …
=> feat: added beta factor support in VAE CV
