- mlcvs/TODO.md
- mlcvs/lda/deep_lda.py
- mlcvs/models/nn.py
- mlcvs/tests/test_lda_deep.py
- mlcvs/tests/test_lda_linear.py
- mlcvs/tests/test_tica_deep.py
- mlcvs/tica/__init__.py
- mlcvs/tica/deep_tica.py
- mlcvs/tica/linear_tica.py
- mlcvs/tica/tica.py
- mlcvs/utils/data.py
- mlcvs/utils/optim.py
added functions for training deepTICA CVs and regtests
> DeepTICA cvs

- docs/_templates/custom-class-template.rst
- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/requirements.yaml
- mlcvs/TODO.md
- mlcvs/lda/deep_lda.py
- mlcvs/lda/linear_lda.py
- mlcvs/models/linear.py
- mlcvs/models/nn.py
- mlcvs/tests/test_lda_deep.py
- mlcvs/tests/test_lda_linear.py
- mlcvs/tests/test_tica_deep.py
- mlcvs/tests/test_tica_linear.py
- mlcvs/tica/deep_tica.py
- mlcvs/tica/linear_tica.py
- mlcvs/utils/data.py
added fit and predict methods for all classes
> scikit-learn style fit and predict

- mlcvs/ae/__init__.py
- mlcvs/ae/ae.py
- mlcvs/models/utils.py
- mlcvs/tests/test_ae.py
- mlcvs/tests/test_lda_deep.py
- mlcvs/tests/test_tica_deep.py
- mlcvs/tests/test_tica_linear.py
> add autoencoder cv

- mlcvs/core/loss/eigvals.py
- mlcvs/cvs/cv.py
- mlcvs/cvs/supervised/deeplda_cv.py
- mlcvs/cvs/supervised/deeptda_cv.py
- mlcvs/cvs/supervised/regression_cv.py
- mlcvs/cvs/timelagged/deeptica_cv.py
- mlcvs/cvs/unsupervised/autoencoder.py
- mlcvs/cvs/unsupervised/vae.py
Reorganized BaseCV with properties and simplified things.
> Change base cv attributes

- mlcvs/core/stats/__init__.py
- mlcvs/core/stats/lda.py
- mlcvs/core/stats/pca.py
- mlcvs/tests/test_core_stats_pca.py
> Add PCA method

- mlcolvar/__init__.py
- mlcolvar/core/nn/utils.py
- mlcolvar/core/stats/tica.py
- mlcolvar/core/transform/utils.py
- mlcolvar/cvs/supervised/deeptda.py
- mlcolvar/cvs/unsupervised/autoencoder.py
- mlcolvar/cvs/unsupervised/vae.py
- mlcolvar/utils/fes.py
- mlcolvar/utils/io.py
- mlcolvar/utils/plot.py
- mlcolvar/utils/timelagged.py
> Code fixes

- mlcolvar/core/stats/tica.py
- mlcolvar/core/stats/utils.py
- mlcolvar/cvs/supervised/deeplda.py
- mlcolvar/data/dataloader.py
- mlcolvar/tests/test_utils_data_dataloader.py
- mlcolvar/tests/test_utils_data_datamodule.py
- Fix #47
- Remove some warnings about invalid escape sequences in docstrings.
> Support for multiple datasets of different size

- .github/workflows/CI.yaml
Debug codecov 0% coverage, issue as in Issue #60
> Codecov_debug

- mlcolvar/cvs/unsupervised/autoencoder.py
Fix AutoEncoder calling pre/postprocessing during training.
> Fix AutoEncoder calling pre/postprocessing during training

- pyproject.toml
> fix dependencies in pyproject

- devtools/conda-envs/test_env.yaml
- docs/requirements.yaml
- pyproject.toml
added scipy version requirement < 1.11 to avoid incompatibility with kdepy (see #84)
> added scipy version requirement 

- docs/notebooks/paper_experiments/paper_2_supervised.ipynb
- Fixes missing axes in paper supervised notebook that caused the failure of CI
- Fixes random split bug as in #91 
- fix doc @luigibonati
> Minor fixes

- README.md
Changed link in CI badge to fix bug, see #94
> Fix bug in CI badge

- devtools/conda-envs/test_env.yaml
- docs/requirements.yaml
Checking whether the conflict between the latest scipy version and kdepy has been fixed (see #84)
> remove version check on scipy

- mlcolvar/cvs/cv.py
- mlcolvar/tests/test_cvs.py
> Fix #103: CVs cannot be loaded from checkpoint

- mlcolvar/cvs/cv.py
- mlcolvar/tests/test_cvs.py
Fix bug in lr_scheduler in configure_optimizer in the base CV class to solve #115
> Fix bug in lr scheduler configure

- mlcolvar/tests/test_cvs.py
Fix issue with automatic device assignation in checkpoint tests
> Fix device issue checkpoint test

- docs/notebooks/tutorials/intro_1_training.ipynb
- mlcolvar/core/transform/descriptors/torsional_angle.py
- mlcolvar/core/transform/descriptors/utils.py
- mlcolvar/cvs/committor/committor.py
Fix few bugs in transform and committor modules.
Committor now runs the forward also in the training step to apply the preprocessing if present.
> Bug fix transform and committor

- mlcolvar/core/loss/committor_loss.py
Fix small bug in committor loss
> Fixed deltaF bug

- docs/notebooks/examples/ex_committor.ipynb
- docs/notebooks/tutorials/adv_transforms.ipynb
- docs/tutorials_advanced.rst
Added transform tutorial, closes #148
[ ] update committor tutorial with multiple transforms
> Improve transform tutorial coverage

- docs/index.rst
- docs/notebooks/tutorials/cvs_committor.ipynb
- docs/requirements.yaml
Added torch_scatter and numpy version to docs requirement file.
Otherwise the latest readthedocs would not compile.
> Fixed docs requirements

- docs/notebooks/examples/ex_committor.ipynb
Fixes headers of committor notebook
> Fixed markdown headers

- docs/notebooks/examples/ex_committor.ipynb
- docs/notebooks/tutorials/cvs_committor.ipynb
The colab links of the  committor needed to be fixed to the main branch
> Fixed colab links

- mlcolvar/core/transform/descriptors/utils.py
Allows applying a cutoff to distances list
> Add cutoff on distances lists

- mlcolvar/utils/fes.py
Fix the transpose issue for the FES when considering a 2D fes with blocks>1 (#191)
> fix fes transpose issue

- mlcolvar/core/transform/descriptors/torsional_angle.py
Fix potential issue related to indices of torsional angles. Fixes #168
> Improve transform
